version: '3.4'

services:
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
  task-auth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"
  task-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventBusConnection=${SERVICE_BUS:-rabbitmq}
    ports:
      - "8001:80"
  subtask-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventBusConnection=${SERVICE_BUS:-rabbitmq}
    ports:
      - "8002:80"
  taskapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - taskapi=http://task-api
      - subtaskapi=http://subtask-api
    ports:
      - "8003:80"